name: Build Docker Image and Upload Artifact

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t my-app:latest .
          docker save my-app:latest -o my-app-image.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-image
          path: my-app-image.tar
          retention-days: 7  # 可根据需要调整保留时间
